spring.application.name=iam-service
spring.config.import=optional:configserver:http://localhost:9001
eureka.client.service-url.defaultZone=http://admin:admin123@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# SpringDoc - advertise gateway as server
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.servers[0].url=http://localhost:9002
springdoc.servers[0].description=Travel360 API Gateway
