spring.application.name=billing-payment-service
spring.config.import=optional:configserver:http://localhost:9001
eureka.client.service-url.defaultZone=http://admin:admin123@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

server.port=9007

spring.datasource.url=jdbc:mysql://localhost:3306/travel_billing_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=dHJhdmVsTWFuYWdlbWVudFN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5HZW5lcmF0aW9uMjAyNFdpdGhFeHRyYUxlbmd0aA==
jwt.expiration=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.servers[0].url=http://localhost:9002
springdoc.servers[0].description=Travel360 API Gateway

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

logging.level.com.travel.billing=DEBUG
